language: php

php:
  - 5.6
  - 7.0
  - 7.1

services:
  - mysql

before_install:
  - sudo apt-get update > /dev/null
  - sudo apt-get install apache2 -y
  - composer self-update
  - composer global require drush/drush:8

install:
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - export DRUPAL_ROOT="$HOME/build/$TRAVIS_REPO_SLUG/drupal-7.x-dev"
  - drush dl drupal-7.x
  - cd $DRUPAL_ROOT
  - drush site-install -y --db-url=mysql://root@127.0.0.1/travisdb --db-su='root' --db-su-pw=''
  - cd $DRUPAL_ROOT/sites/all/modules
  - git clone https://github.com/isumoc/brilliant_gallery_mysql.git
  - drush pm-enable brilliant_gallery -y
  - drush cc all --yes
  - drush status

before_script:
  - drush runserver 127.0.0.1:8080 &

script: /bin/true
